# .pre-commit-config.yaml
-   repo: https://github.com/pre-commit/mirrors-ruff
    rev: v0.0.235
    hooks:
    -   id: ruff

-   repo: https://github.com/pre-commit/mirrors-black
    rev: v22.3.0
    hooks:
    -   id: black
      language_version: python3

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
      language_version: python3
