services:
  db:
    image: postgres:16-alpine
    container_name: spacex_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=spacex_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d spacex_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl_app:
      build: .
      container_name: spacex_pipeline
      restart: always
      depends_on:
        db:
          condition: service_healthy
      environment:
        - POSTGRES_HOST=db
        - PYTHONPATH=/app
        
        - PREFECT_API_KEY=${PREFECT_API_KEY}
        - PREFECT_API_URL=${PREFECT_API_URL}
        - POSTGRES_HOST=db
        - PREFECT_CLIENT_TIMEOUT=60

      env_file:
        - .env


volumes:
  postgres_data: