version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: spacex_postgres
    restart: always
    env_file: .env
    networks:
      - backend
    healthcheck:
      # Corrigida a sintaxe de escape para variáveis de ambiente no shell do Docker
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # MAPEAMENTO VITAL: O arquivo local init.sql deve estar na mesma pasta deste compose
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  etl_app:
    build: .
    container_name: spacex_pipeline
    depends_on:
      db:
        condition: service_healthy # O app só inicia quando o DB estiver pronto e tabelas criadas
    env_file: .env
    environment:
      - POSTGRES_HOST=db
    networks:
      - backend
      - internet
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  backend:
    internal: true # Segurança: O DB não é exposto para a internet
  internet:
    driver: bridge # Necessário para o app buscar dados na API da SpaceX

volumes:
  postgres_data: # Persistência de dados