version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: spacex_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=spacex_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d spacex_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl_app:
    build: .
    container_name: spacex_pipeline
    depends_on:
      db:
        condition: service_healthy
    environment:
      - "DATABASE_URL=postgresql://postgres:admin@db:5432/spacex_db"
      - "PYTHONPATH=/app:/app/src"
    volumes:
      - .:/app

volumes:
  postgres_data: