version: '3.8'

services:
  etl_pipeline:
    build: .
    container_name: spacex_etl_container
    # Removed 'ports' since ETL scripts don't need an open port
    volumes:
      # MAPPING: Local folder : Folder in Container
      # This ensures that the .db and logs appear in your VS Code
      - ./data:/app/data
    env_file:
      - .env
