services:
  db:
    image: postgres:16-alpine
    container_name: spacex_postgres
    restart: always
    env_file: .env # All credentials (USER, PASS, DB) come from this file
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s # 5s is too aggressive for some environments
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  etl_app:
    build: .
    container_name: spacex_pipeline
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - PYTHONPATH=/app
      - POSTGRES_HOST=db
      - INSIDE_DOCKER=1
    networks:
      - frontend_network
      - backend_network

networks:
  frontend_network: # Internet access (SpaceX API + Prefect Cloud)
  backend_network:  # Isolated (ETL <-> Postgres communication)
    #internal: true

volumes:
  postgres_data:
