version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: spacex_postgres
    restart: always
    env_file: .env
    networks:
      - private_network
    healthcheck:
      # Corrigido escape do $ para variáveis de ambiente do shell do postgres
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  etl_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: spacex_pipeline
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    # Sobrescrevemos o HOST para o nome do serviço no docker
    environment:
      - POSTGRES_HOST=db
      - DBT_PROFILES_DIR=/app/dbt
    networks:
      - private_network
    volumes:
      - etl_logs:/app/logs
    restart: on-failure
    # Comando corrigido para rodar como módulo e respeitar o loop de 1h
    command: >
      sh -c "
      while true; do
        python -m src.flows.etl_flow;
        echo 'Ciclo finalizado. Aguardando 1 hora...';
        sleep 3600;
      done"

networks:
  private_network:
    driver: bridge

volumes:
  postgres_data:
  etl_logs:
