version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: spacex_postgres
    restart: always
    env_file: .env
    networks:
      - private_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-spacex_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  etl_app:
    build: 
      context: .
      dockerfile: Dockerfile  
    container_name: spacex_pipeline
    depends_on:
      db:
        condition: service_healthy
    env_file: .env  # Carrega as variáveis do .env
    environment:
      - POSTGRES_HOST=db  # Usando o nome do serviço Docker como host do banco
      - DBT_PROFILES_DIR=/app/dbt
    networks:
      - private_network
    volumes:
      - .:/app
      - etl_logs:/app/logs
    restart: on-failure
    
    command: 
      - sh
      - -c
      - |
        while true; do
          python -m src.flows.etl_flow
          echo "Ciclo finalizado. Aguardando 1 hora..."
          sleep 3600
        done

networks:
  private_network:
    driver: bridge

volumes:
  postgres_data:
  etl_logs: