name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  #Lint
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - run: |
          pip install ruff
          ruff check .

  # Type checking
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - run: |
          pip install mypy
          mypy src

  # Testes com PostgreSQL
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: spacex_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d spacex_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      INSIDE_DOCKER: 0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spacex_db
      POSTGRES_HOST_INTERNAL: localhost
      POSTGRES_HOST_EXTERNAL: localhost
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done
      - run: pytest -v --maxfail=1 --disable-warnings

  # Build Docker
  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t spacex-etl .

  # Data Quality 
  data-quality:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - run: |
          pip install -e .[dev]
          pip install great_expectations
      - run: |
          python -m src.etl.data_quality_check
